=== getporter/porter/pkg/schema/credential-set.schema.json
{
    "$id": "https://cnab.io/v1/credential-set.schema.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
      "valueMapping": {
        "description": "Defines the source for a value",
        "type": "object",
        "properties": {
          "name": {
            "description": "Name of the mapped value",
            "type": "string"
          },
          "source": {
            "description": "Location where the value should be retrieved",
            "type": "object",
            "properties": {
              "command": {
                "description": "Command that should be executed on the host, using the output returned from the command as the value",
                "type": "string"
              },
              "env": {
                "description": "Name of the environment variable on the host that contains the value",
                "type": "string"
              },
              "path": {
                "description": "Path to a file on the host that contains the value",
                "type": "string"
              },
              "secret": {
                "description": "Name of a secret in a secret store that contains the value",
                "type": "string"
              },
              "value": {
                "description": "Hard-coded value",
                "type": "string"
              }
            },
            "additionalProperties": true
          }
        },
        "additionalProperties": false,
        "required": ["name", "source"]
      }
    },
    "properties": {
      "name": {
        "description": "The name of the credential set.",
        "type": "string"
      },
      "created": {
        "description": "The date created, as an ISO-8601 Extended Format date string, as specified in the ECMAScript standard",
        "type": "string"
      },
      "modified": {
        "description": "The date modified, as an ISO-8601 Extended Format date string, as specified in the ECMAScript standard",
        "type": "string"
      },
      "credentials": {
        "description": "Mappings of parameter names to their source value", 
        "type": "array",
        "items": {
          "$ref": "#/definitions/valueMapping"
        }
      },
      "custom": {
        "$comment": "reserved for custom extensions",
        "type": "object",
        "additionalProperties": true
      },
      "schemaVersion": {
        "description": "Version of the credential set schema to which this document adheres",
        "type": "string",
        "default": "1.0.0"
      }
    },
    "required": [
      "name",
      "created",
      "modified",
      "credentials",
      "schemaVersion"
    ],
    "title": "CNAB Credential Set json schema",
    "type": "object",
    "additionalProperties": false
  }

=== getporter/porter/pkg/storage/testdata/migrated/credentials/mybun.json
{
  "schemaVersion": "1.0.0",
  "name": "mybun",
  "created": "2020-01-01T00:00:00Z",
  "modified": "2020-01-01T00:00:00Z",
  "credentials": [
    {
      "name": "CLIENT_ID",
      "source": {
        "env": "OAUTH_CLIENT_ID"
      }
    },
    {
      "name": "CLIENT_SECRET",
      "source": {
        "env": "OAUTH_CLIENT_SECRET"
      }
    }
  ]
}
