=== getporter/porter/pkg/schema/parameter-set.schema.json
{
  "$id": "https://porter.sh/schema/v1/parameter-set.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "valueMapping": {
      "description": "Defines the source for a value",
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the mapped value",
          "type": "string"
        },
        "source": {
          "description": "Location where the value should be retrieved",
          "type": "object",
          "properties": {
            "command": {
              "description": "Command that should be executed on the host, using the output returned from the command as the value",
              "type": "string"
            },
            "env": {
              "description": "Name of the environment variable on the host that contains the value",
              "type": "string"
            },
            "path": {
              "description": "Path to a file on the host that contains the value",
              "type": "string"
            },
            "secret": {
              "description": "Name of a secret in a secret store that contains the value",
              "type": "string"
            },
            "value": {
              "description": "Hard-coded value",
              "type": "string"
            }
          },
          "additionalProperties": true
        }
      },
      "additionalProperties": false,
      "required": ["name", "source"]
    }
  },
  "properties": {
    "name": {
      "description": "The name of the parameter set.",
      "type": "string"
    },
    "namespace": {
      "description": "The namespace in which the parameter set is defined.",
      "type": "string"
    },
    "created": {
      "description": "The date created, as an ISO-8601 Extended Format date string, as specified in the ECMAScript standard",
      "type": "string"
    },
    "modified": {
      "description": "The date modified, as an ISO-8601 Extended Format date string, as specified in the ECMAScript standard",
      "type": "string"
    },
    "labels": {
      "description": "Set of labels associated with the parameter set.",
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "parameters": {
      "description": "Mappings of parameter names to their source value", 
      "type": "array",
      "items": {
        "$ref": "#/definitions/valueMapping"
      }
    },
    "custom": {
      "$comment": "reserved for custom extensions",
      "type": "object",
      "additionalProperties": true
    },
    "schemaType": {
      "description": "The resource type of the current document.",
      "type": "string",
      "default": "ParameterSet"
    },
    "schemaVersion": {
      "description": "Version of the parameter set schema to which this document adheres",
      "type": "string",
      "default": "1.0.1"
    }
  },
  "required": [
    "name",
    "parameters",
    "schemaVersion"
  ],
  "title": "Parameter Set json schema",
  "type": "object",
  "additionalProperties": false
}

=== getporter/porter/pkg/templates/templates/parameters/create/parameter-set.json
{
    "schemaType": "ParameterSet",
    "schemaVersion": "1.0.1",
    "name": "NAME",
    "namespace": "NAMESPACE",
    "labels": {
        "LABEL": "LABEL_VALUE"
    },
    "parameters": [
        {
            "name": "parameter-path",
            "source": {
                "path": "/path/to/parameter-path-file.txt"
            }
        },
        {
            "name": "parameter-command",
            "source": {
                "command": "echo 'parameter command'"
            }
        },
        {
            "name": "parameter-env",
            "source": {
                "env": "PARAMETER_ENV"
            }
        },
        {
            "name": "parameter-value",
            "source": {
                "value": "parametervalue"
            }
        },
        {
            "name": "parameter-secret",
            "source": {
                "secret": "parameter-secret"
            }
        }
    ]
}

=== getporter/porter/pkg/storage/testdata/migrated/parameters/mybun.json
{
  "schemaVersion": "1.0.0",
  "name": "mybun",
  "created": "2020-01-01T00:00:00Z",
  "modified": "2020-01-01T00:00:00Z",
  "parameters": [
    {
      "name": "verbose",
      "source": {
        "value": "6"
      }
    },
    {
      "name": "db-password",
      "source": {
        "secret": "mysql-password"
      }
    }
  ]
}

=== getporter/porter/pkg/parameters/testdata/paramset.json
{
  "schemaVersion": "1.0.0",
  "name": "mybun",
  "created": "1983-04-18T01:02:03.000000004Z",
  "modified": "1983-04-18T01:02:03.000000004Z",
  "parameters": [
    {
      "name": "param_env",
      "source": {
        "env": "PARAM_ENV"
      }
    },
    {
      "name": "param_value",
      "source": {
        "value": "param_value"
      }
    },
    {
      "name": "param_command",
      "source": {
        "command": "echo hello world"
      }
    },
    {
      "name": "param_path",
      "source": {
        "path": "/path/to/param"
      }
    },
    {
      "name": "param_secret",
      "source": {
        "secret": "param_secret"
      }
    }
  ]
}
