=== getporter/porter/pkg/templates/templates/credentials/create/credential-set.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "valueMapping": {
            "description": "Defines the source for a value",
            "type": "object",
            "properties": {
                "name": {
                    "description": "Name of the mapped value",
                    "type": "string"
                },
                "source": {
                    "description": "Location where the value should be retrieved",
                    "type": "object",
                    "properties": {
                        "command": {
                            "description": "Command that should be executed on the host, using the output returned from the command as the value",
                            "type": "string"
                        },
                        "env": {
                            "description": "Name of the environment variable on the host that contains the value",
                            "type": "string"
                        },
                        "path": {
                            "description": "Path to a file on the host that contains the value",
                            "type": "string"
                        },
                        "secret": {
                            "description": "Name of a secret in a secret store that contains the value",
                            "type": "string"
                        },
                        "value": {
                            "description": "Hard-coded value",
                            "type": "string"
                        }
                    },
                    "additionalProperties": true
                }
            },
            "additionalProperties": false,
            "required": [
                "name",
                "source"
            ]
        }
    },
    "properties": {
        "name": {
            "description": "The name of the credential set.",
            "type": "string"
        },
        "namespace": {
            "description": "The namespace in which the credential set is defined.",
            "type": "string"
        },
        "labels": {
            "description": "Set of labels associated with the credential set.",
            "type": "object",
            "additionalProperties": {
                "type": "string"
            }
        },
        "credentials": {
            "description": "Mappings of parameter names to their source value",
            "type": "array",
            "items": {
                "$ref": "#/definitions/valueMapping"
            }
        },
        "schemaType": {
            "description": "The resource type of the current document.",
            "type": "string",
            "default": "CredentialSet"
        },
        "schemaVersion": {
            "description": "Version of the credential set schema to which this document adheres",
            "type": "string",
            "default": "1.0.0"
        }
    },
    "required": [
        "name",
        "credentials",
        "schemaVersion"
    ],
    "title": "Credential Set json schema",
    "type": "object",
    "additionalProperties": false
}

=== getporter/porter/pkg/templates/templates/credentials/create/credential-set.json
{
    "schemaType": "CredentialSet",
    "schemaVersion": "1.0.0",
    "name": "NAME",
    "namespace": "NAMESPACE",
    "labels": {
        "LABEL": "LABEL_VALUE"
    },
    "credentials": [
        {
            "name": "credential-path",
            "source": {
                "path": "/path/to/credential-path-file.txt"
            }
        },
        {
            "name": "credential-command",
            "source": {
                "command": "echo 'credential command'"
            }
        },
        {
            "name": "credential-env",
            "source": {
                "ENV": "CREDENTIAL_ENV"
            }
        },
        {
            "name": "credential-value",
            "source": {
                "value": "credentialvalue"
            }
        },
        {
            "name": "credential-secret",
            "source": {
                "secret": "credential-secret"
            }
        }
    ]
}
